### ISSUE TITLE
Returning to "Select Remote" -- cannot choose new project/folder w double click

### ISSUE THREAD

**Issue by drowenhorst-nrl** [BlueQuartzSoftware/MetaForge#21]
Need two projects, P1 and P2, with folders F1 and F2 respectively.
Select P1/F1 and upload file.  
Return to "Select Remote" 
Chose P2/F2 
Get an error.  Looks like it is not refreshing the folder path when a new project is selected.  
```
Traceback (most recent call last):
  File "/Users/dave/PycharmProjects/MetaForge/MetaForge/hyperthoughtdialogimpl.py", line 117, in ascendingDirectories
    folderlist = ht_requests.get_item_dict_from_ht_path(self.authcontrol, 
  File "/Users/dave/PycharmProjects/MetaForge/MetaForge/ht_requests/ht_requests/ht_requests.py", line 86, in get_item_dict_from_ht_path
    ht_id_path = get_ht_id_path_from_ht_path(auth_control, ht_path=ht_path,\
  File "/Users/dave/PycharmProjects/MetaForge/MetaForge/ht_requests/ht_requests/ht_requests.py", line 163, in get_ht_id_path_from_ht_path
    raise FileNotFoundError(f'Could not find file/folder located at {ht_path} in HyperThought: {comp} does not exist!')
FileNotFoundError: Could not find file/folder located at /F1/F2/ in HyperThought: F1 does not exist!
```

**Comment by drowenhorst-nrl** [comment]
IMPORTANT NOTE: 
Get an error on double-click into P2/F2 

If just single-click on P2/F2 it appears to be selected properly.  This is a problem if you need to get to P2/F2/FF2

**Comment by imikejackson** [comment]
macOS Catalina has refresh issues. We are trying to solve the refresh/repaint issues. The code has also been rewritten so this should be fixed now.
